### ISSUE TITLE
'node_modules' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by jinglerobs** [ChrisPhillips-cminion/APIConnect-ImpactAnalysis#7]
==================================
D:\APICwork\APIConnect-ImpactAnalysis>npm cache clean
D:\APICwork\APIConnect-ImpactAnalysis>node apicia.js
? API Connect Management Server? us.apiconnect.ibmcloud.com
? Username robin.thomas@cognizant.com
? Password ************
| Logging in...ERR: Error: Command failed: node_modules/.bin/apic login --userna
me robin.thomas@cognizant.com --password ****** --server us.apiconnect.ibmcloud.
com
'node_modules' is not recognized as an internal or external command,
operable program or batch file.

x Logging in...
[Error: Failed to log into APIC, please see previous error message for details]

D:\APICwork\APIConnect-ImpactAnalysis>apic --version
API Connect: v5.0.6.2 (apiconnect: v2.5.21)
===========================================

**Comment by ChrisPhillips-cminion** [comment]
can you please do a dir /s  in that directory so i can get the tree available.  I  have made some assumptions for windows as I only have access to unix system at the moment.

**Comment by ChrisPhillips-cminion** [comment]
Thanks, I know the issue will try and fix shortly.

**Comment by jinglerobs** [comment]
Thanks Chris ☺

Regards,
Robin C Thomas | Cognizant India Limited
Ph: +91 721 809 1822
robin.thomas@cognizant.com<mailto:robin.thomas@cognizant.com>

**Comment by ChrisPhillips-cminion** [comment]
I do not have a windows vm to hand to test this.

I have put a fix on my second account  (yes i know i should have branched but there were reasons for this) https://github.com/phillip3-automated/APIConnect-ImpactAnalysis if you want to give it a try. I will try and get hold of a windows box shortly.

**Comment by jinglerobs** [comment]
===============================================
D:\APICwork\APIConnect-ImpactAnalysis>npm cache clean

D:\APICwork\APIConnect-ImpactAnalysis>node apicia.js
? API Connect Management Server? us.apiconnect.ibmcloud.com
? Username robin.thomas@cognizant.com
? Password ************
| Logging in...D:\APICwork\APIConnect-ImpactAnalysis\lib\functions.js:45
            throw err;
            ^

Error: Command failed: node_modules\.bin\apic login --username robin.thomas@cogn
izant.com --password ******** --server us.apiconnect.ibmcloud.com

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:854:16)
    at Socket.<anonymous> (internal/child_process.js:330:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:487:12)

D:\APICwork\APIConnect-ImpactAnalysis>
======================================================

**Comment by ChrisPhillips-cminion** [comment]
I have made a change and I am now seeing this. I am running it through my local automated tests for unix to ensure I have not broken anything and then it will be pushed to the other git.  Ideally i need to fix the spinner for downloading the yaml however this is not critical. 


`C:\APIConnect-ImpactAnalysis-master>node apicia.js
? API Connect Management Server? eu-de.apiconnect.ibmcloud.com
? Username chris.phillips@uk.ibm.com
? Password ************
√ Logging in...
√ Fetching organizations
? Please select the target organization: chrisphillipsukibmcom-germanspace
√ Fetching catalogs for organization: chrisphillipsukibmcom-germanspace
? Please select the target catalog: sb
√ Get DisplayName for Catalog : sb
? Please select which data you wish to show: (Press <space> to select, <a> to t
oggle all, <i> to inverse selection, <left> to move entry up, <right> to move e
ntry down)API, Service - Host / QueueManager, Service - ContextRoute / Queue, P
roduct, Plan, Application
? Do you want to save this config: No
Begin downloadYamlForProduct function for sb
- Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
\ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
| Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
/ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
- Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
\ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
| Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
/ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
- Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
\ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
| Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
/ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
- Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
\ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
| Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
/ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
- Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
\ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
| Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
/ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
- Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
\ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
| Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
/ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
- Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
\ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
| Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
/ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
- Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
\ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
| Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
/ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
- Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
\ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
| Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
/ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
- Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
\ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
| Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
/ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
- Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
\ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
| Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
/ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
- Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
\ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
| Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
/ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
- Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
\ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
| Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
/ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
- Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
\ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
| Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
√ Downloading Product sb:climbing-weather-api-product:1.0.0 this may take a few
minutes...
Processing Complete for sb

Results of analysis:
────────────────────────────────────────


Sandbox
└────>API - Climbing Weather API : 1.0.0
        └────>Service Host - https://api.us.apiconnect.ibmcloud.com
                └────>Service ContextRoute - /developmentoperations-apiconnect/s
b$(request.path)$(request.search)&client_id=1666be44-048e-4658-b525-d9329e7c48d0
                        └────>Product - Climbing Weather API product : 1.0.0
                                └────>Plan - Default Plan`

**Comment by ChrisPhillips-cminion** [comment]
This is now pushed

**Comment by jinglerobs** [comment]
Different error
========================================

D:\APICwork\apicia>node apicia.js
? API Connect Management Server? us.apiconnect.ibmcloud.com
? Username robin.thomas@cognizant.com
? Password ************
| Logging in...D:\APICwork\apicia\lib\functions.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";var f
=module.exports={},exec=require("child_process").exec,fs=require("fs.extra"),con
fig=require("./config.js"),terminal=require("window-size"),Ora=require("ora"),wi
dth=terminal.width/2,divideLine="─".repeat(width),apicLogin=require("./apicLogin
");Array.prototype.contains=function(e){for(var o=this.length;o--;)if(this[o].na
me===e)return!0;return!1},f.printDivideLine=function(){console.error(divideLine+
"\n")},f.call=function(e,o){config.debug&&console.error(e.includes("password")?"
This f.call command has not been logged as it contains password information":"Be
gin f.call function with command: "+e),exec(e,{},function(e,r,n){if(e)throw e;re
turn o(e,r,n)})},f.cd=function(e){f.isDir(e)?(config.debug&&console.error("Chang
ing directory to: "+e),process.chdir(e)):fs.mkdir(e,function(o){o&&console.error
(o),config.debug&&console.error("Changing directory to: "+e),process.chdir(e)})}
,f.makeSpinner=functio

Error: Command failed: node_modules\.bin\apic login --username robin.thomas@cogn
izant.com --password ******** --server us.apiconnect.ibmcloud.com

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:854:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
=================================================================

**Comment by ChrisPhillips-cminion** [comment]
Added additional debug please try again.

**Comment by jinglerobs** [comment]
=====================================================
D:\APICwork\apicia>node apicia.js
? API Connect Management Server? us.apiconnect.ibmcloud.com
? Username robin.thomas@cognizant.com
? Password ************
/ Logging in...
Error: Login to us.apiconnect.ibmcloud.com failed. Please verify the server and
credentials.

ERR: Error: Command failed: node_modules\.bin\apic login --username "robin.thoma
s@cognizant.com" --password "*******" --server "us.apiconnect.ibmcloud.com"

x Logging in...
[Error: Failed to log into APIC, please see previous error message for details]

D:\APICwork\apicia>
========================================================

**Comment by ChrisPhillips-cminion** [comment]
OK can you please check your username and password. 

If you are certain hte password is correct can you confirm you have an API Connect service deployed in the US bluemix.

node_modules.bin\apic login --username "robin.thomas@cognizant.com" --password "*******" --server "us.apiconnect.ibmcloud.com" obviously setting the password. 

If you are still sure everything is correct can you please look in the .apiconnect/apic.og log on unix this is stored in home directory

I have had this working against bluemix with my own account.

**Comment by jinglerobs** [comment]
Username/password are correct and API connect service is up and running in Bluemix. Does the management login connection to Bluemix go over SSH/telnet ?

**Comment by ChrisPhillips-cminion** [comment]
No we use the apic command line.

To be exact this command.
apic login --username "robin.thomas@cognizant.com" --password "*******" --server "us.apiconnect.ibmcloud.com"

Can you test this command? 

if the command above does work then we are not handling special characters in your password, so i will need to investigate further.

**Comment by ChrisPhillips-cminion** [comment]
apic login --username "chris.phillips@uk.ibm.com" --password "******"  --server "us.apiconnect.ibmcloud.com"   works fine for me

**Comment by ChrisPhillips-cminion** [comment]
Any luck?

**Comment by jinglerobs** [comment]
Username/password is working on GUI login to Bluemix, but not working through apic command line ☹

Thanks & Regards,
Robin C Thomas | Cognizant India Limited
Ph: +91 721 809 1822
robin.thomas@cognizant.com<mailto:robin.thomas@cognizant.com>

**Comment by ChrisPhillips-cminion** [comment]
Have you tried putting " around your password?

**Comment by jinglerobs** [comment]
Yes, tried putting “ as well, but no luck ☹

Thanks & Regards,
Robin C Thomas | Cognizant India Limited
Ph: +91 721 809 1822
robin.thomas@cognizant.com<mailto:robin.thomas@cognizant.com>

**Comment by ChrisPhillips-cminion** [comment]
There was a known issue with Bluemix that was fixed recently. I have asked them to confirm the fix was applied. Could you retry

**Comment by jinglerobs** [comment]
Got logged in from home network, suspect some firewall issue from office network.

Still getting an error while fetching the API option
=======================================
D:\APICwork\apicia>node apicia.js
? API Connect Management Server? us.apiconnect.ibmcloud.com
? Username robin.thomas@cognizant.com
? Password ************
√ Logging in...
√ Fetching organizations
? Please select the target organization: cts-commtech-o2smipfbd-1000136916
√ Fetching catalogs for organization: cts-commtech-o2smipfbd-1000136916
? Please select the target catalog:
? Please select which data you wish to show: (Press <space> to select, <a> to t
oggle all, <i> to inverse selection, <left> to move entry up, <right> to move e
ntry down)
? Do you want to save this config: No

Results of analysis:
────────────────────────────────────────


D:\APICwork\apicia\node_modules\graceful-fs\polyfills.js:21
  chdir.call(process, d)
        ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (D:\APICwork\apicia\node_modules\graceful-fs\polyfills.js:2
1:9)
    at D:\APICwork\apicia\lib\functions.js:1:1028
    at FSReqWrap.oncomplete (fs.js:82:15)

D:\APICwork\apicia>
===================================================

**Comment by ChrisPhillips-cminion** [comment]
Do you have permission to write to that directory with the user running the node app? Can you create a tmp directory in there with full write permissions and try agian. Also can you please select some data to show.

**Comment by jinglerobs** [comment]
I m running the node commands with administrative access, also have given full read/write permission to folder. I have created a 'tmp' folder as well. Now I m able to login to see the organization and  view the catalogs. When I select the catalog there are some options to choose from.

=================================================

D:\APICwork\apicia>node apicia.js
? API Connect Management Server? us.apiconnect.ibmcloud.com
? Username robin.thomas@cognizant.com
? Password ************
√ Logging in...
√ Fetching organizations
? Please select the target organization: cts-commtech-o2smipfbd-1000136916
√ Fetching catalogs for organization: cts-commtech-o2smipfbd-1000136916
? Please select the target catalog: (Press <space> to select, <a> to toggle all
, <i> to inverse selection)
>( ) production
 ( ) sb
 ( ) swaggerhub001


? Please select which data you wish to show: (Press <space> to select, <a> to t
oggle all, <i> to inverse selection, <left> to move entry up, <right> to move e
ntry down)
>( ) Service - Host / QueueManager
 ( ) Service - ContextRoute / Queue
 ( ) API
 ( ) Product
 ( ) Plan
 ( ) Application
=================================================

Regardless of whichever option I select, the 'Result of Analysis' is empty always
=====================================
[a.txt](https://github.com/ChrisPhillips-cminion/APIConnect-ImpactAnalysis/files/981164/a.txt)
[b.txt](https://github.com/ChrisPhillips-cminion/APIConnect-ImpactAnalysis/files/981165/b.txt)


Results of analysis:
────────────────────────────────────────

==========================================

**Comment by ChrisPhillips-cminion** [comment]
Sorry missed the bit in bold will take a look Monday 
 
 Sent from my iPhone using IBM Verse
 
 On May 6, 2017, 9:50:37 PM, notifications@github.com wrote:

**Comment by ChrisPhillips-cminion** [comment]
You need to select an option in the the final screen. I should make an action not to accept nothing 
 
 Sent from my iPhone using IBM Verse
 
 On May 6, 2017, 9:50:37 PM, notifications@github.com wrote:

**Comment by ChrisPhillips-cminion** [comment]
The display option is not set, did you set anything in the last set if of options?
 
 Sent from my iPhone using IBM Verse
 
 On May 6, 2017, 9:50:37 PM, notifications@github.com wrote:

**Comment by jinglerobs** [comment]
Nopes, did not set any options, just selected using down arrows one of the available options.

Thanks & Regards,
Robin C Thomas | Cognizant India Limited
Ph: +91 721 809 1822
robin.thomas@cognizant.com<mailto:robin.thomas@cognizant.com>

**Comment by ChrisPhillips-cminion** [comment]
You need to press space to select one of the options before you press enter. 
 
 Sent from my iPhone using IBM Verse
 
 On May 7, 2017, 4:32:10 PM, notifications@github.com wrote:

**Comment by ChrisPhillips-cminion** [comment]
I have finally managed to reproduce a similar issue. Currently this only detects published APIs with that use the invoke or the mq invoke policies.

**Comment by venosov** [comment]
Same problem, I can log in bluemix with "apic login", but with apicia:

✖ Logging in...
[Error: Failed to log into APIC, please see previous error message for details]

**Comment by ChrisPhillips-cminion** [comment]
Does your password contain a " ? if so that may need escaping

**Comment by venosov** [comment]
It doesn't :-(

**Comment by venosov** [comment]
I saw it, the problem is the language, my apic uses Spanish ("Inicio de sesión en XXX satisfactorio") and the check "e.match(/^Logged into/)" fails.

**Comment by ChrisPhillips-cminion** [comment]
Thanks Venosov, I will create a new issue to track this.
